### ISSUE TITLE
Fiche "KICKOFF" du projet

### ISSUE THREAD

**Issue by JolanThomassin** [cegepmatane/projet-specialise-2022-JolanThomassin#1]
Compléter la fiche et répondre à ces questions :
 - [x] quelle est la technologie qui sera utilisée pour implémenter l'API en tant que tel ?
 - [x] quelle est la base de données qui conservera les informations ?
 - [x] quel est le format d'échange de données avec l'API ? xml ? json ? autre ?
 - [x] est-ce que l'algorithme du bot est plus un système expert (je crois)) ou plus une ia ?
 - [x] quelle librairie vas-tu prendre pour tenter de parser les questions reçues par le bot ?

**Comment by nadineprofesseur** [comment]
https://github.com/cegepmatane/projet-specialise-2022-JolanThomassin/commit/1b357497fa534a5c2cd4c45f9b5138203ed4090d
